'use client';

import { useState, useEffect } from 'react';
import { X, Copy, Check, Share2, MessageSquare, Edit3 } from 'lucide-react';

export interface WhatsAppReminderData {
  title: string;
  targetTime?: string | null;
  creativeUrl?: string | null;
  hasMedia?: boolean;
  caption?: string | null;
}

interface WhatsAppReminderModalProps {
  data: WhatsAppReminderData;
  isOpen?: boolean;
  onClose: () => void;
}

export default function WhatsAppReminderModal({
  data,
  isOpen = true,
  onClose,
}: WhatsAppReminderModalProps) {
  const [message, setMessage] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!data) return;

    const isMediaReady = Boolean(data.creativeUrl || data.hasMedia);
    const isCaptionReady = Boolean(data.caption && data.caption.trim().length > 0);
    const targetTime = data.targetTime || '12:00';

    let msg = `📢 Today's Reminder\n\n📌 Event:\n${data.title.trim()}\n\n🕒 Provisional Posting Time:\n${targetTime}\n\n🎨 Media:\n${
      isMediaReady ? '✅ READY' : '❌ NOT YET READY'
    }\n\n✍ Caption:\n${isCaptionReady ? '✅ READY' : '❌ NOT YET READY'}\n\n`;

    if (isCaptionReady) {
      msg += `━━━━━━━━━━━━━━━━━━━━━━\n\nCaption\n\n${data.caption!.trim()}\n\n━━━━━━━━━━━━━━━━━━━━━━\n\n`;
    }

    msg += `Generated by ClubHQ`;

    setMessage(msg);
  }, [data]);

  if (!isOpen) return null;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(message);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error('Failed to copy text:', err);
    }
  };

  const handleShareToWhatsApp = () => {
    const encodedText = encodeURIComponent(message);
    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodedText}`;
    window.open(whatsappUrl, '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#244855]/70 backdrop-blur-sm">
      <div className="relative w-full max-w-lg sit-card bg-white border border-[#244855]/15 rounded-2xl shadow-2xl overflow-hidden text-[#244855] max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#244855]/10 bg-[#244855] text-white">
          <div className="flex items-center space-x-2.5">
            <div className="p-2 rounded-lg bg-[#E64833] text-white shadow-sm">
              <MessageSquare className="h-5 w-5" />
            </div>
            <div>
              <h3 className="text-sm font-extrabold text-white">Reminder Preview</h3>
              <p className="text-xs text-white/80 font-medium">Review and edit message before sending</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-white/80 hover:text-white rounded-lg hover:bg-white/10 transition-colors"
            title="Close"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content Body / Text Editor */}
        <div className="p-6 space-y-4 bg-[#FFF8F5]/60 flex-1 overflow-y-auto">
          <div className="flex items-center justify-between text-xs">
            <span className="font-extrabold text-[#244855] flex items-center gap-1.5">
              <Edit3 className="w-3.5 h-3.5 text-[#E64833]" /> Edit Generated Reminder:
            </span>
            <span className="text-[11px] text-[#244855]/60 font-semibold font-mono">
              ClubHQ Reminder System
            </span>
          </div>

          <textarea
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            rows={11}
            className="w-full p-4 rounded-xl bg-[#244855] text-xs sm:text-sm text-white font-mono whitespace-pre-wrap leading-relaxed border border-[#244855] focus:outline-none focus:ring-2 focus:ring-[#E64833] resize-y"
          />
        </div>

        {/* Footer Actions */}
        <div className="flex flex-wrap items-center justify-end gap-2.5 px-6 py-4 border-t border-[#244855]/10 bg-white">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-bold btn-outline"
          >
            Cancel
          </button>

          <button
            onClick={handleCopy}
            className={`inline-flex items-center space-x-1.5 px-4 py-2 rounded-xl text-xs font-bold transition-all border ${
              copied
                ? 'bg-emerald-100 text-emerald-800 border-emerald-300'
                : 'btn-outline'
            }`}
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 text-emerald-600" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                <span>Copy Message</span>
              </>
            )}
          </button>

          <button
            onClick={handleShareToWhatsApp}
            className="inline-flex items-center space-x-1.5 px-4 py-2.5 rounded-xl text-xs font-bold bg-[#25D366] hover:bg-[#20bd5a] text-white shadow-md transition-all"
          >
            <Share2 className="h-4 w-4" />
            <span>Share to WhatsApp</span>
          </button>
        </div>
      </div>
    </div>
  );
}
